"""initial migration

Revision ID: 6c2a82bcfe4a
Revises: 
Create Date: 2026-06-02 20:50:56.936691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c2a82bcfe4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    ##op.drop_table('clients')
    op.execute('DROP TABLE clients CASCADE')
    op.add_column('cost_codes', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cost_codes_cost_code_id'), 'cost_codes', ['cost_code_id'], unique=False)
    op.create_foreign_key(None, 'cost_codes', 'companies', ['company_id'], ['company_id'])
    op.add_column('employees', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('trade_level', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['company_id'])
    op.create_index(op.f('ix_job_budgets_budget_id'), 'job_budgets', ['budget_id'], unique=False)
    op.add_column('jobs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('province', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('budgeted_hours', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('budgeted_materials_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    ##op.drop_constraint(op.f('jobs_client_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['company_id'])
    op.drop_column('jobs', 'start_date')
    op.drop_column('jobs', 'client_id')
    op.drop_column('jobs', 'job_address')
    op.drop_column('jobs', 'end_date')
    op.add_column('materials', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('purchased_by', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('supplier', sa.String(length=255), nullable=True))
    op.add_column('materials', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.add_column('materials', sa.Column('receipt_image_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_materials_material_id'), 'materials', ['material_id'], unique=False)
    op.drop_constraint(op.f('materials_logged_by_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'employees', ['purchased_by'], ['employee_id'])
    op.create_foreign_key(None, 'materials', 'companies', ['company_id'], ['company_id'])
    op.drop_column('materials', 'logged_date')
    op.drop_column('materials', 'logged_by')
    op.add_column('timesheets', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('timesheets', sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_index(op.f('ix_timesheets_timesheet_id'), 'timesheets', ['timesheet_id'], unique=False)
    op.create_foreign_key(None, 'timesheets', 'companies', ['company_id'], ['company_id'])
    op.drop_column('timesheets', 'custom_data')
    op.drop_column('timesheets', 'material_needs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('material_needs', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('timesheets', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'timesheets', type_='foreignkey')
    op.drop_index(op.f('ix_timesheets_timesheet_id'), table_name='timesheets')
    op.drop_column('timesheets', 'overtime_hours')
    op.drop_column('timesheets', 'company_id')
    op.add_column('materials', sa.Column('logged_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('logged_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_logged_by_fkey'), 'materials', 'employees', ['logged_by'], ['employee_id'])
    op.drop_index(op.f('ix_materials_material_id'), table_name='materials')
    op.drop_column('materials', 'receipt_image_url')
    op.drop_column('materials', 'purchase_date')
    op.drop_column('materials', 'supplier')
    op.drop_column('materials', 'purchased_by')
    op.drop_column('materials', 'company_id')
    op.add_column('jobs', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('job_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_client_id_fkey'), 'jobs', 'clients', ['client_id'], ['client_id'])
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_column('jobs', 'budgeted_materials_cost')
    op.drop_column('jobs', 'budgeted_hours')
    op.drop_column('jobs', 'postal_code')
    op.drop_column('jobs', 'province')
    op.drop_column('jobs', 'city')
    op.drop_column('jobs', 'street')
    op.drop_column('jobs', 'company_id')
    op.drop_index(op.f('ix_job_budgets_budget_id'), table_name='job_budgets')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_column('employees', 'trade_level')
    op.drop_column('employees', 'company_id')
    op.drop_constraint(None, 'cost_codes', type_='foreignkey')
    op.drop_index(op.f('ix_cost_codes_cost_code_id'), table_name='cost_codes')
    op.drop_column('cost_codes', 'company_id')
    op.create_table('clients',
    sa.Column('client_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('client_id', name=op.f('clients_pkey'))
    )
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
