"""add trial fields to company

Revision ID: 91d364bc2ff0
Revises: f9caad15fcd1
Create Date: 2026-06-05 18:43:06.480905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d364bc2ff0'
down_revision: Union[str, Sequence[str], None] = 'f9caad15fcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('companies', sa.Column('trial_start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('companies', sa.Column('trial_status', sa.String(length=50), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('timesheets', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('materials', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('cost_codes', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.alter_column('cost_codes', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('companies', 'trial_status')
    op.drop_column('companies', 'trial_start_date')
    # ### end Alembic commands ###
